//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Author = newAuthorTable("public", "Author", "")

type authorTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	Name      postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AuthorTable struct {
	authorTable

	EXCLUDED authorTable
}

// AS creates new AuthorTable with assigned alias
func (a AuthorTable) AS(alias string) *AuthorTable {
	return newAuthorTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuthorTable with assigned schema name
func (a AuthorTable) FromSchema(schemaName string) *AuthorTable {
	return newAuthorTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuthorTable with assigned table prefix
func (a AuthorTable) WithPrefix(prefix string) *AuthorTable {
	return newAuthorTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuthorTable with assigned table suffix
func (a AuthorTable) WithSuffix(suffix string) *AuthorTable {
	return newAuthorTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuthorTable(schemaName, tableName, alias string) *AuthorTable {
	return &AuthorTable{
		authorTable: newAuthorTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newAuthorTableImpl("", "excluded", ""),
	}
}

func newAuthorTableImpl(schemaName, tableName, alias string) authorTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		NameColumn      = postgres.StringColumn("name")
		CreatedAtColumn = postgres.TimestampColumn("createdAt")
		UpdatedAtColumn = postgres.TimestampColumn("updatedAt")
		allColumns      = postgres.ColumnList{IDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return authorTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
